import 'package:flutter/material.dart';

abstract class Palette {
  Color get appBarColor;
  Color get appBarTextColor;
  Color get appBarIconColor;
  Color get globalScaffoldBackgroundcolor;
  Color get cardColor;
  Color get switchColor;
  Color get iconColor;
  Color get switchTrackColorActive;
  Color get switchTrackInactiveColor;

  Color get answerSelectedColor;
  Color get answerCorrectColor;
  Color get answerIncorrectColor;
}

/// This Palette is used to define the colors used in the app.
/// and is generated by coolers.co
/// ["526DA1","D7DCE2","070D6C","03034B","383294"]
class BluePalette implements Palette {
  BluePalette._private();
  static final _instance = BluePalette._private();
  factory BluePalette() {
    return _instance;
  }
  @override
  Color get appBarColor => const Color(0xFF070D6C);
  @override
  Color get appBarTextColor => const Color(0xFFD7DCE2);
  @override
  Color get appBarIconColor => const Color(0xFFD7DCE2);

  @override
  Color get globalScaffoldBackgroundcolor => const Color(0xFFD7DCE2);

  @override
  Color get cardColor => const Color(0xFF383294);

  @override
  Color get iconColor => const Color(0xFF383294);
  @override
  Color get switchColor => const Color(0xFF383294);
  @override
  Color get switchTrackColorActive => const Color(0xFF526DA1);

  @override
  Color get switchTrackInactiveColor => const Color(0xFFFAF3DD);

  @override
  Color get answerCorrectColor => Colors.greenAccent;

  @override
  Color get answerIncorrectColor => Colors.redAccent;

  @override
  Color get answerSelectedColor => appBarColor;
}
